###
GET http://localhost:3001/api/bean 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMzc3NTRiODkzZTk5YTc4ZDY0MjYzNCIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTU5ODg1NzYxMn0.6axxOhfR3rZl0yyGS4VLKvnNHbxJLnev9VCrsJuF2GY
